baseurl = "https://www.briheet.com"
enableEmoji = true
footnotereturnlinkcontents = "â†©"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Home"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Blogs"
url = "/blogs/"
weight = 1

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "[Github](https://github.com/briheet) | [X](https://x.com/brsy_10) | [Linkedin](https://www.linkedin.com/in/briheet-singh-yadav/)"
